import { WebUiFormField } from '@biztobiz/web-ui/form'
import React from 'react'
import {
  AdminChaptersDocument,
  AdminCompaniesDocument,
  Role,
  UserOnlineStatus,
  UserStatus,
} from '@biztobiz/shared/util-sdk'

// TODO: Create custom filter functions
// function regionFilterFunction(regions: Region[]) {
//   return regions?.filter((region) => !region.User?.id)
// }

export const userFields: WebUiFormField[] = [
  WebUiFormField.datePicker('lastSeen', { label: 'Last Seen' }),
  WebUiFormField.enumSelect('onlineStatus', {
    label: 'Online Status',
    required: true,
    defaultValue: UserOnlineStatus.Offline,
    enum: UserOnlineStatus,
  }),
  WebUiFormField.enumSelect('status', {
    label: 'User Status',
    required: true,
    defaultValue: UserStatus.Pending,
    enum: UserStatus,
  }),
  WebUiFormField.checkbox('developer', { label: 'Is the user a Developer?' }),
  WebUiFormField.enumSelect('role', { label: 'User Role', required: true, defaultValue: Role.User, enum: Role }),
  WebUiFormField.email('email', { label: 'Email' }),
  WebUiFormField.checkbox('emailConfirmed', { label: 'Email Confirmed?' }),
  WebUiFormField.input('username', { label: 'Username' }),
  WebUiFormField.number('infusionsoftId', { label: 'Infusionsoft Id' }),
  WebUiFormField.input('firstName', { label: 'First Name' }),
  WebUiFormField.input('lastName', { label: 'Last Name' }),
  WebUiFormField.input('password', { label: 'Password' }),
  WebUiFormField.input('passwordResetToken', { label: 'Password Reset Token' }),
  WebUiFormField.datePicker('passwordResetExpires', { label: 'Password Reset Expires' }),
  WebUiFormField.input('confirmEmailToken', { label: 'Confirm Email Token' }),
  WebUiFormField.datePicker('confirmEmailExpires', { label: 'Confirm Email Expires' }),
  WebUiFormField.switch('showGravatar', { label: 'Show Gravatar' }),
  WebUiFormField.input('avatarUrl', { label: 'Avatar Url' }),
  WebUiFormField.datePicker('applicationDate', { label: 'Application Date' }),
  WebUiFormField.datePicker('inactiveDate', { label: 'Inactive Date' }),
  WebUiFormField.datePicker('inquiryDate', { label: 'Inquiry Date' }),
  WebUiFormField.datePicker('membershipDate', { label: 'Membership Date' }),
  WebUiFormField.datePicker('renewalDate', { label: 'Renewal Date' }),
  WebUiFormField.datePicker('terminationDate', { label: 'Termination Date' }),
  WebUiFormField.datePicker('transferDate', { label: 'Transfer Date' }),
  WebUiFormField.input('location', { label: 'Location' }),
  WebUiFormField.input('phone', { label: 'Phone' }),
  WebUiFormField.input('bio', { label: 'Bio' }),
  WebUiFormField.input('facebook', { label: 'Facebook' }),
  WebUiFormField.input('twitter', { label: 'Twitter' }),
  WebUiFormField.input('youtube', { label: 'Youtube' }),
  WebUiFormField.input('linkedin', { label: 'LinkedIn' }),
  WebUiFormField.input('instagram', { label: 'Instagram' }),
  WebUiFormField.input('website', { label: 'Website' }),
  WebUiFormField.input('industry', { label: 'Industry' }),
  WebUiFormField.input('timeInIndustry', { label: 'Time in Industry' }),
  WebUiFormField.input('address', { label: 'Address' }),
  WebUiFormField.input('address2', { label: 'Address Line 2' }),
  WebUiFormField.input('cell', { label: 'Mobile Phone' }),
  WebUiFormField.input('chapterTitle', { label: 'Chapter Title' }),
  WebUiFormField.input('city', { label: 'City' }),
  WebUiFormField.input('comments', { label: 'Comments' }),
  WebUiFormField.input('company', { label: 'Company' }),
  WebUiFormField.input('fax', { label: 'Fax' }),
  WebUiFormField.input('hear', { label: 'How did you hear about us?' }),
  WebUiFormField.input('hearOther', { label: 'How did you hear about us? (Other)' }),
  WebUiFormField.input('internalComments', { label: 'Internal Comments' }),
  WebUiFormField.checkbox('launchComplete', { label: 'Launch Complete' }),
  WebUiFormField.input('mentorName', { label: 'Mentor Name' }),
  WebUiFormField.input('merchantCircle', { label: 'Merchant Circle' }),
  WebUiFormField.checkbox('multipleBusinesses', { label: 'Multiple Businesses' }),
  WebUiFormField.checkbox('multipleLocations', { label: 'Multiple Locations' }),
  WebUiFormField.input('numberOfEmployees', { label: 'Number of Employees' }),
  WebUiFormField.input('organizer', { label: 'Organizer' }),
  WebUiFormField.input('otherBusinesses', { label: 'Other Businesses' }),
  WebUiFormField.input('otherLocations', { label: 'Other Locations' }),
  WebUiFormField.input('postCode', { label: 'Zip Code' }),
  WebUiFormField.input('promoter', { label: 'Promoter' }),
  WebUiFormField.input('recognized', { label: 'Recognized' }),
  WebUiFormField.input('salesAgentName', { label: 'Sales Agent Name' }),
  WebUiFormField.input('state', { label: 'State' }),
  WebUiFormField.input('strategizer', { label: 'Strategizer' }),
  WebUiFormField.checkbox('substitute', { label: 'Substitute' }),
  WebUiFormField.input('tagline', { label: 'Tagline' }),
  WebUiFormField.input('terminatedByName', { label: 'Terminated By Name' }),
  WebUiFormField.input('terminationComments', { label: 'Termination Comments' }),
  WebUiFormField.input('terminationReason', { label: 'Termination Reason' }),
  WebUiFormField.input('thinker', { label: 'Thinker' }),
  WebUiFormField.input('title', { label: 'Title' }),
  WebUiFormField.input('type', { label: 'Type' }),
  WebUiFormField.checkbox('vet', { label: 'Vet' }),
  WebUiFormField.checkbox('notifyByEmail', { label: 'Notify by Email' }),
  WebUiFormField.checkbox('notifyBySMS', { label: 'Notify by SMS' }),
  WebUiFormField.checkbox('notifyByWeb', { label: 'Notify by Web' }),
  WebUiFormField.checkbox('notifyByMobile', { label: 'Notify by Mobile' }),
  WebUiFormField.relationSelect('chapterId', {
    label: 'Chapter',
    document: AdminChaptersDocument,
    dataType: 'chapters',
  }),
  WebUiFormField.relationSelect('companies', {
    label: 'Companies',
    document: AdminCompaniesDocument,
    dataType: 'companies',
    multi: true,
  }),
]
